### ISSUE TITLE
Feature request: Multiple limbo servers

### ISSUE THREAD

**Issue by CappyT** [McMackety/velocity-queue#10]
I suggest the idea of having multiple limbo servers.
This is useful for very large networks, allowing to spread the queue load on multiple servers and thus allowing to have a much larger queue.

I don't really know the effort needed for such a feature as it needs queue sync between limbo servers to keep priorities.

**Comment by McMackety** [comment]
That shouldn’t be terrible, but as of now I still haven’t gotten to the previous issue cause lab classes are slamming me with work right now. Will try to do this and the other feature request this weekend.

**Comment by McMackety** [comment]
I just realized I added this feature quite a while ago, it will randomly distribute the players among all the limbo servers in the list. Sorry for taking so long to close this lol.

**Comment by CappyT** [comment]
Many thanks for the effort!
