### ISSUE TITLE
Send the player back to the server.

### ISSUE THREAD

**Issue by KoxSosen** [McMackety/velocity-queue#11]
Hello!

I got the plugin working with no issues. When a player joins, he gets sent to the backend server if there's space. If there isn't it sends him to the limbo, and adds him to the queue. If there's space, he moves them in.

However, if I kick the player out of the backend server, and in the velocity config I have 

```try=["backend", "limbo"]``` configured, it won't send me back to the backend server if there's space for some reason. Only if I reconnect. 

If I remove the limbo option from the try feature, players can't join the server when the backend is down/they where on it when it shut down-

Please add an option to check if the player was kicked from the server, but still in the network, and add them to the queue, like they just joined. Thank you!

**Comment by KoxSosen** [comment]
I really need the try feature.

**Comment by McMackety** [comment]
Alright, I can listen to a player-kicked event and then redirect them back into the join queue. The reason this doesn't work currently is that the join queue can only be appended by somebody literally connecting to the proxy. Will try to do this tonight as it's the easiest fix to do. But I am busy most of this week so possible not.

**Comment by KoxSosen** [comment]
If it's an easy fix, please do that soon!

**Comment by McMackety** [comment]
Well, turns out this is not an easy fix because velocity hides the `try` field from plugins. Currently, I'm trying to access the config and write my own server picker.

**Comment by KoxSosen** [comment]
What do you think, is it doable?

**Comment by McMackety** [comment]
Yes, but I need to write a new function that replicates the function in Velocity's internals for picking the initial server..

**Comment by KoxSosen** [comment]
Oh, sounds complicated. How will this affect the performance of the plugin?

**Comment by McMackety** [comment]
Just figured out a way around it, testing the changes now.

**Comment by McMackety** [comment]
The changes work, pushing and releasing now. The test I did wasn't comprehensive so be careful.

**Comment by McMackety** [comment]
Done!
https://github.com/McMackety/velocity-queue/releases/tag/v1.0.4

**Comment by McMackety** [comment]
Just realized there was an issue with the build I uploaded, if you downloaded the release prior to this message redownload it.

**Comment by KoxSosen** [comment]
Worked thank you!!
