### ISSUE TITLE
The player kick method does not works

### ISSUE THREAD

**Issue by KoxSosen** [McMackety/velocity-queue#12]
I updated the plugin to the latest jar. Restarted both velocity and the backend server. 

Now if I join to the server, I get sent to the backend. If I stop the backend server, I get moved to the limbo server, but for some reason it does not adds me to the queue, neither I get moved to backend from the limbo once it's up again.

**Comment by KoxSosen** [comment]
I'm using the latest velocity with 1.16.5, and modern fowarding.

**Comment by McMackety** [comment]
Ahhh, I can’t get to it till tonight, sorry for the issue I don’t own an actual network so I can’t do proper at scale tests. Though I think that you aren’t kicked when a server gets down but instead there’s a different event, I’ll figure out that event and fix it tonight.

**Comment by KoxSosen** [comment]
Thank you!

**Comment by McMackety** [comment]
This might be a very late night thing, I've got two essays due by midnight so this is on my back burner till after then.

**Comment by KoxSosen** [comment]
Take your time, no rush mate! Good luck with the exams!

**Comment by McMackety** [comment]
I just tested it and it worked for me, remove the `limbo` from your try servers, as it most likely is putting you in that server because the main one is down, however the queue should already put you into the limbo when the main server is down.

**Comment by KoxSosen** [comment]
http://prntscr.com/106gxna

If I remove limbo from the try list, I get kicked from the network instead of getting sent to the limbo.

**Comment by KoxSosen** [comment]
The main point is, to when the backend server tops/kick the player, he gets moved to the limbo where he queues up to the backend.
