### ISSUE TITLE
Feature Request: Add priorities

### ISSUE THREAD

**Issue by Tyguh** [McMackety/velocity-queue#13]
Can you add a permission-based priority system to the intra-queue instead?

**Comment by Tyguh** [comment]
Any opinions on this @McMackety?

**Comment by McMackety** [comment]
I mean, this would be a harder feature to implement. As I need to calculate a score for each player based on their priority and the amount of time they've been in the queue. Then order the players based on that score. As of right now it'll be a solid week before I do this, got a lot of stuff to do this week.

**Comment by McMackety** [comment]
Just added this today, it needs to be tested on a server with more than one player but it seems to work.
