### ISSUE TITLE
The main point is, to when the backend server tops/kick the player, he gets moved to the limbo where he queues up to the backend.

### ISSUE THREAD

**Issue by KoxSosen** [McMackety/velocity-queue#14]
The main point is, to when the backend server tops/kick the player, he gets moved to the limbo where he queues up to the backend.

_Originally posted by @KoxSosen in https://github.com/McMackety/velocity-queue/issues/12#issuecomment-785807621_

**Comment by McMackety** [comment]
Yes, if you remove the limbo from the try field they will still be put in the limbo when a server goes down. It’s just that right now they are being put in a queue to go to the limbo server, which errors out and nothing happens.

**Comment by McMackety** [comment]
That’s all you need to do to get the behavior you want, the plug-in needs no modification.

**Comment by KoxSosen** [comment]
http://prntscr.com/106gxna

**Comment by KoxSosen** [comment]
It kicks me when it goes down

**Comment by McMackety** [comment]
Hmm, will look at it, might be another bug.

**Comment by KoxSosen** [comment]
Thank you!

**Comment by McMackety** [comment]
Well, now that I finally got to look into this, you were right, the kicking functionality doesn't work. Fixing now.

**Comment by McMackety** [comment]
It's now fixed, pushing and creating a new release now.

**Comment by McMackety** [comment]
Fixed in https://github.com/McMackety/velocity-queue/releases/tag/v1.0.5
