### ISSUE TITLE
Can't connect to limbo when using forced hosts

### ISSUE THREAD

**Issue by roccodev** [McMackety/velocity-queue#15]
When a player joins one of the "queued" servers through a forced host and the (queued) server is full, the player is just stuck on "Logging in". Velocity log shows they're online, but the limbo server doesn't get a connection.

**Comment by roccodev** [comment]
Sorry, forgot to mention: join queue is disabled, the intra-server queue isn't working.

**Comment by McMackety** [comment]
Alright, tonight I finally have a couple of hours to throw into this project so I'll debug it tonight. Though that's most likely because `PlayerChooseInitialServerEvent` isn't called when using a forced host.

**Comment by McMackety** [comment]
My initial thoughts were correct, the issue was ServerPreConnect was being called and not the initial one. Just fixed it and will link to the release here once built. (Sorry for taking so long, haven't had much time to work on this recently.)

**Comment by McMackety** [comment]
Here's the release: https://github.com/McMackety/velocity-queue/releases/tag/v1.0.6
