### ISSUE TITLE
No limbo servers are registered, couldn't send _Pixel0 to a limbo server.

### ISSUE THREAD

**Issue by flerouwu** [McMackety/velocity-queue#16]
Hello!

This issue is similar to #7 however everything that was mentioned there did not work for me. I am using [this ](https://www.spigotmc.org/resources/limbo-standalone-server-lightweight-solution-for-afk-or-waiting-rooms-in-your-server-network.82468/)software for the limbo server with legacy forwarding. Thanks.

**Comment by McMackety** [comment]
Did you try the solution put within that other issue?

**Comment by flerouwu** [comment]
Yes, I did

**Comment by McMackety** [comment]
Can you send me your Velocity config (without the shared secret) and your Queue plugin config, I'm don't really have enough information to debug without that this as my configuration works fine.
