### ISSUE TITLE
Message templates do not work

### ISSUE THREAD

**Issue by Cubxity** [McMackety/velocity-queue#3]
Message templates such as `<index></index>` do not work as intended. Tested on Velocity 1.1.2

**Comment by McMackety** [comment]
Hmm, it is defined in my code, let me see if placeholders are used differently in Minimessage.
![image](https://user-images.githubusercontent.com/43187891/102951363-b0fdaf80-449a-11eb-8d19-d66f96e1a075.png)

**Comment by McMackety** [comment]
Whoops, yeah I read that wrong. This is the format it should be in: 
![image](https://user-images.githubusercontent.com/43187891/102951660-603a8680-449b-11eb-8dea-df856cb4198d.png)
That means it would be `{index}`.

I'm updating the README now, thanks for catching that!

**Comment by McMackety** [comment]
Well, it actually is `<index>` not `{index}`, had to dive even further into the code to find that. They really should add some docs to the page.
