### ISSUE TITLE
Plugin isn't working.

### ISSUE THREAD

**Issue by KoxSosen** [McMackety/velocity-queue#4]
Issue:
I'm connected to the limbo, but I do not get into the queue.
What I'm trying to archive:
Upon joining I get into the limbo. In the limbo I get queued into the survival server instantly, regardless of how many players are in the survival server.

Configs:
Veloctiy Queue config:

![image](https://user-images.githubusercontent.com/67807644/103619175-8814fa00-4f31-11eb-911a-79adefe3b1b3.png)

Velocity:

![image](https://user-images.githubusercontent.com/67807644/103619276-ba265c00-4f31-11eb-9e5a-86e724811a56.png)

Limbo:

![image](https://user-images.githubusercontent.com/67807644/103619350-d6c29400-4f31-11eb-88eb-0f9b87ee2fda.png)

All servers are using MODERN velocity fowarding. I don't even see the message that I joined into the queue when I join the limbo, and does not get moved either.

**Comment by McMackety** [comment]
Let me try reproducing it, if you have any errors that would be helpful.

**Comment by McMackety** [comment]
Oh, your limbo server and initial server are the same. That means it is erroring out from sending you to the server you are already on. You need to set the `try = ["limbo"]` to `try = ["survival"]` for it to work.

**Comment by KoxSosen** [comment]
Thank you, I will try.
