### ISSUE TITLE
The queue bypass is only working for admins and not the other roles with the permission

### ISSUE THREAD

**Issue by Jmaster426** [McMackety/velocity-queue#8]
Is there a way to fix this? Im just curious because a perk for a donator role is queue bypass but the permission doesn't seem to be working?

**Comment by McMackety** [comment]
Wait, so the permission does work for the admin role but doesn't for the donator role?

**Comment by Jmaster426** [comment]
Yea, im confused about how it should work. I thought players with that permission could bypass the player cap on the queued server.

**Comment by McMackety** [comment]
They are, as long as the player **can join the backend server when it is full**. As the backend server will still deny connections when full. This means you need a plugin on the backend to allow this. Use something like https://www.spigotmc.org/resources/simplereserve.22327/.

**Comment by Jmaster426** [comment]
Oh ok, I will try it but idk if it will work for 1.16.4 which is the version my server is on
